name: Process Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    permissions:
      pull-requests: read

    runs-on: ubuntu-latest
    steps:
    - name: Fetch Dependabot metadata
      id: dependabot-metadata
      uses: dependabot/fetch-metadata@v1.4.0
    - uses: actions/checkout@v3.5.2
    - name: Update Version Number in Other Files
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: ${{ steps.dependabot-metadata.outputs.previous-version }}
        replace: ${{ steps.dependabot-metadata.outputs.new-version }}
        regex: false
    - name: Push Changes to PR
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}