name: Process Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    permissions:
      pull-requests: write

    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    - name: Fetch Dependabot metadata
      id: dependabot-metadata
      uses: dependabot/fetch-metadata@v1.4.0
    - uses: actions/checkout@v3.5.2
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Update Version Number in Other Files
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: ${{ steps.dependabot-metadata.outputs.previous-version }}
        replace: ${{ steps.dependabot-metadata.outputs.new-version }}
        regex: false
    - name: Commit & Push Changes to PR
      uses: EndBug/add-and-commit@v9.1.3
      message: 'Update version number in other files'